// Code generated by aru model:build from model.go. DO NOT EDIT.

package tags

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Taggables starts a query on the table of Taggable, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Taggables(db model.DB) *TaggableQuery { return &TaggableQuery{b: taggableTable.Query(db)} }

// TaggableQuery is a query on the table of Taggable.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Taggable rows or a value; there is
// no way to run one without a Grant.
type TaggableQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of model.go -- and for the
// factory, which builds rows through it.
func (q *TaggableQuery) Base() *model.Builder { return q.b }

// New returns an empty Taggable on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *TaggableQuery) New() (*Taggable, error) {
	e, err := q.b.NewModelInstance(nil)
	return taggableOf(e), err
}

// TaggableCollection is rows of Taggable, as a query returns them.
type TaggableCollection []*Taggable

// TaggableCollectionOf converts rows of the table of Taggable. A nil input is a nil
// collection.
func TaggableCollectionOf(rows model.Rows) TaggableCollection {
	if rows == nil {
		return nil
	}
	out := make(TaggableCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Taggable)
	}
	return out
}

func taggableOf(e model.Entity) *Taggable {
	row, _ := e.(*Taggable)
	return row
}

// taggableColumn turns a closure over TaggableQuery into one over the core builder, so
// passing func(*TaggableQuery) where a column goes adds a parenthesised group.
func taggableColumn(column any) any {
	if group, ok := column.(func(*TaggableQuery)); ok {
		return func(b *model.Builder) { group(&TaggableQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *TaggableQuery) Clone() *TaggableQuery { return &TaggableQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*TaggableQuery) in place of the column adds a group.
func (q *TaggableQuery) Where(column any, args ...any) *TaggableQuery {
	q.b.Where(taggableColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*TaggableQuery) in place of the column adds a group.
func (q *TaggableQuery) OrWhere(column any, args ...any) *TaggableQuery {
	q.b.OrWhere(taggableColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *TaggableQuery) WhereNot(column any, args ...any) *TaggableQuery {
	q.b.WhereNot(taggableColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *TaggableQuery) OrWhereNot(column any, args ...any) *TaggableQuery {
	q.b.OrWhereNot(taggableColumn(column), args...)
	return q
}

func (q *TaggableQuery) WhereIn(column any, values []any) *TaggableQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *TaggableQuery) WhereNotIn(column any, values []any) *TaggableQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *TaggableQuery) WhereNull(columns ...any) *TaggableQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *TaggableQuery) WhereNotNull(columns ...any) *TaggableQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *TaggableQuery) WhereBetween(column any, from, to any) *TaggableQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *TaggableQuery) WhereColumn(first any, args ...any) *TaggableQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *TaggableQuery) WhereKey(id any) *TaggableQuery {
	q.b.WhereKey(id)
	return q
}

func (q *TaggableQuery) WhereExists(callback func(*query.Builder)) *TaggableQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *TaggableQuery) WhereNotExists(callback func(*query.Builder)) *TaggableQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *TaggableQuery) WhereHas(relation string, callback func(*query.Builder)) *TaggableQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *TaggableQuery) OrWhereHas(relation string, callback func(*query.Builder)) *TaggableQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *TaggableQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *TaggableQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *TaggableQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *TaggableQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *TaggableQuery) WhereRelation(relation string, column any, args ...any) *TaggableQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *TaggableQuery) OrWhereRelation(relation string, column any, args ...any) *TaggableQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *TaggableQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *TaggableQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *TaggableQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *TaggableQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *TaggableQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *TaggableQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *TaggableQuery) OrHas(relation, operator string, count int) *TaggableQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *TaggableQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *TaggableQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *TaggableQuery) OrDoesntHave(relation string) *TaggableQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *TaggableQuery) Select(columns ...any) *TaggableQuery {
	q.b.Select(columns...)
	return q
}

func (q *TaggableQuery) AddSelect(columns ...any) *TaggableQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *TaggableQuery) SelectRaw(expression string, bindings ...any) *TaggableQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *TaggableQuery) Join(table any, first any, args ...any) *TaggableQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *TaggableQuery) GroupBy(groups ...any) *TaggableQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *TaggableQuery) OrderBy(column any, direction ...string) *TaggableQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *TaggableQuery) OrderByDesc(column any) *TaggableQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *TaggableQuery) Latest(column ...string) *TaggableQuery {
	q.b.Latest(column...)
	return q
}

func (q *TaggableQuery) Oldest(column ...string) *TaggableQuery {
	q.b.Oldest(column...)
	return q
}

func (q *TaggableQuery) Limit(value int) *TaggableQuery {
	q.b.Limit(value)
	return q
}

func (q *TaggableQuery) Offset(value int) *TaggableQuery {
	q.b.Offset(value)
	return q
}

func (q *TaggableQuery) ForPage(page, perPage int) *TaggableQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *TaggableQuery) With(relations ...string) *TaggableQuery {
	q.b.With(relations...)
	return q
}

func (q *TaggableQuery) WithCount(relations ...string) *TaggableQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *TaggableQuery) WithExists(relation string) *TaggableQuery {
	q.b.WithExists(relation)
	return q
}

func (q *TaggableQuery) WithSum(relation, column string) *TaggableQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *TaggableQuery) WithAvg(relation, column string) *TaggableQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *TaggableQuery) WithMin(relation, column string) *TaggableQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *TaggableQuery) WithMax(relation, column string) *TaggableQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *TaggableQuery) Without(relations ...string) *TaggableQuery {
	q.b.Without(relations...)
	return q
}

func (q *TaggableQuery) WithoutGlobalScope(identifier string) *TaggableQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *TaggableQuery) WithoutGlobalScopes(identifiers ...string) *TaggableQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *TaggableQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (TaggableCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return TaggableCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *TaggableQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Taggable, error) {
	e, err := q.b.First(ctx, g, columns...)
	return taggableOf(e), err
}

func (q *TaggableQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Taggable, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return taggableOf(e), err
}

func (q *TaggableQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Taggable, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return taggableOf(e), err
}

func (q *TaggableQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Taggable, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return taggableOf(e), err
}

func (q *TaggableQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Taggable, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return taggableOf(e), err
}

func (q *TaggableQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Taggable, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return taggableOf(e), err
}

func (q *TaggableQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Taggable, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return taggableOf(e), err
}

func (q *TaggableQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Taggable, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return taggableOf(e), err
}

func (q *TaggableQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (TaggableCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return TaggableCollectionOf(rows), err
}

func (q *TaggableQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Taggable, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return taggableOf(e), err
}

func (q *TaggableQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Taggable, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return taggableOf(e), err
}

func (q *TaggableQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Taggable, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return taggableOf(e), err
}

func (q *TaggableQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Taggable, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return taggableOf(e), err
}

func (q *TaggableQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (TaggableCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return TaggableCollectionOf(rows), meta, err
}

func (q *TaggableQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (TaggableCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return TaggableCollectionOf(rows), meta, err
}

func (q *TaggableQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (TaggableCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return TaggableCollectionOf(rows), meta, err
}

func (q *TaggableQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(TaggableCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(TaggableCollectionOf(rows), page)
	})
}

func (q *TaggableQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Taggable, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(taggableOf(e), index)
	})
}

func (q *TaggableQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Taggable, error] {
	return func(yield func(*Taggable, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(taggableOf(e), err) {
				return
			}
		}
	}
}

func (q *TaggableQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *TaggableQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *TaggableQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *TaggableQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *TaggableQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *TaggableQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *TaggableQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *TaggableQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *TaggableQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *TaggableQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *TaggableQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *TaggableQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *TaggableQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *TaggableQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *TaggableQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *TaggableQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *TaggableQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *TaggableQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *TaggableQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c TaggableCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c TaggableCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c TaggableCollection) Find(key any) *Taggable { return taggableOf(c.Rows().Find(key)) }

func (c TaggableCollection) FindOrFail(key any) (*Taggable, error) {
	e, err := c.Rows().FindOrFail(key)
	return taggableOf(e), err
}

func (c TaggableCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c TaggableCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c TaggableCollection) Only(keys ...any) TaggableCollection {
	return TaggableCollectionOf(c.Rows().Only(keys...))
}

func (c TaggableCollection) Except(keys ...any) TaggableCollection {
	return TaggableCollectionOf(c.Rows().Except(keys...))
}

func (c TaggableCollection) Unique() TaggableCollection {
	return TaggableCollectionOf(c.Rows().Unique())
}

func (c TaggableCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c TaggableCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c TaggableCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c TaggableCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (TaggableCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return TaggableCollectionOf(rows), err
}

func (c TaggableCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Taggable; it shadows the untyped one the
// embedded model promotes.
func (row *Taggable) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Taggable, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return taggableOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Taggable) Replicate(except ...string) (*Taggable, error) {
	e, err := row.Model.Replicate(except...)
	return taggableOf(e), err
}
