// Code generated by aru model:build from counter.go. DO NOT EDIT.

package sequence

import (
	"context"
	"iter"

	"github.com/arandu-io/hesape/auth"
	"github.com/arandu-io/hesape/database/model"
	"github.com/arandu-io/hesape/database/query"
	"github.com/arandu-io/hesape/pagination"
)

// Counters starts a query on the table of Counter, through db.
//
// Global scopes are on and, unless the table is Global, every statement is
// filtered by the tenant of the Grant its terminal takes.
func Counters(db model.DB) *CounterQuery { return &CounterQuery{b: counterTable.Query(db)} }

// CounterQuery is a query on the table of Counter.
//
// The methods that build return the query, so they chain. The methods that run
// take a context and an auth.Grant, and return Counter rows or a value; there is
// no way to run one without a Grant.
type CounterQuery struct{ b *model.Builder }

// Base returns the core builder the query forwards to. It is for code in this
// package -- a local scope in the custom block of counter.go -- and for the
// factory, which builds rows through it.
func (q *CounterQuery) Base() *model.Builder { return q.b }

// New returns an empty Counter on the query's connection, not yet saved, filled
// with what WithAttributes recorded on the query.
func (q *CounterQuery) New() (*Counter, error) {
	e, err := q.b.NewModelInstance(nil)
	return counterOf(e), err
}

// CounterCollection is rows of Counter, as a query returns them.
type CounterCollection []*Counter

// CounterCollectionOf converts rows of the table of Counter. A nil input is a nil
// collection.
func CounterCollectionOf(rows model.Rows) CounterCollection {
	if rows == nil {
		return nil
	}
	out := make(CounterCollection, len(rows))
	for i, e := range rows {
		out[i] = e.(*Counter)
	}
	return out
}

func counterOf(e model.Entity) *Counter {
	row, _ := e.(*Counter)
	return row
}

// counterColumn turns a closure over CounterQuery into one over the core builder, so
// passing func(*CounterQuery) where a column goes adds a parenthesised group.
func counterColumn(column any) any {
	if group, ok := column.(func(*CounterQuery)); ok {
		return func(b *model.Builder) { group(&CounterQuery{b: b}) }
	}
	return column
}

// Clone returns an independent copy of the query.
func (q *CounterQuery) Clone() *CounterQuery { return &CounterQuery{b: q.b.Clone()} }

// Where adds a where clause; a func(*CounterQuery) in place of the column adds a group.
func (q *CounterQuery) Where(column any, args ...any) *CounterQuery {
	q.b.Where(counterColumn(column), args...)
	return q
}

// OrWhere adds an or-where clause; a func(*CounterQuery) in place of the column adds a group.
func (q *CounterQuery) OrWhere(column any, args ...any) *CounterQuery {
	q.b.OrWhere(counterColumn(column), args...)
	return q
}

// WhereNot adds a negated where clause, or a negated group.
func (q *CounterQuery) WhereNot(column any, args ...any) *CounterQuery {
	q.b.WhereNot(counterColumn(column), args...)
	return q
}

// OrWhereNot adds an or-joined negated where clause, or a negated group.
func (q *CounterQuery) OrWhereNot(column any, args ...any) *CounterQuery {
	q.b.OrWhereNot(counterColumn(column), args...)
	return q
}

func (q *CounterQuery) WhereIn(column any, values []any) *CounterQuery {
	q.b.WhereIn(column, values)
	return q
}

func (q *CounterQuery) WhereNotIn(column any, values []any) *CounterQuery {
	q.b.WhereNotIn(column, values)
	return q
}

func (q *CounterQuery) WhereNull(columns ...any) *CounterQuery {
	q.b.WhereNull(columns...)
	return q
}

func (q *CounterQuery) WhereNotNull(columns ...any) *CounterQuery {
	q.b.WhereNotNull(columns...)
	return q
}

func (q *CounterQuery) WhereBetween(column any, from, to any) *CounterQuery {
	q.b.WhereBetween(column, from, to)
	return q
}

func (q *CounterQuery) WhereColumn(first any, args ...any) *CounterQuery {
	q.b.WhereColumn(first, args...)
	return q
}

func (q *CounterQuery) WhereKey(id any) *CounterQuery {
	q.b.WhereKey(id)
	return q
}

func (q *CounterQuery) WhereExists(callback func(*query.Builder)) *CounterQuery {
	q.b.WhereExists(callback)
	return q
}

func (q *CounterQuery) WhereNotExists(callback func(*query.Builder)) *CounterQuery {
	q.b.WhereNotExists(callback)
	return q
}

func (q *CounterQuery) WhereHas(relation string, callback func(*query.Builder)) *CounterQuery {
	q.b.WhereHas(relation, callback)
	return q
}

func (q *CounterQuery) OrWhereHas(relation string, callback func(*query.Builder)) *CounterQuery {
	q.b.OrWhereHas(relation, callback)
	return q
}

func (q *CounterQuery) WhereDoesntHave(relation string, callback func(*query.Builder)) *CounterQuery {
	q.b.WhereDoesntHave(relation, callback)
	return q
}

func (q *CounterQuery) OrWhereDoesntHave(relation string, callback func(*query.Builder)) *CounterQuery {
	q.b.OrWhereDoesntHave(relation, callback)
	return q
}

func (q *CounterQuery) WhereRelation(relation string, column any, args ...any) *CounterQuery {
	q.b.WhereRelation(relation, column, args...)
	return q
}

func (q *CounterQuery) OrWhereRelation(relation string, column any, args ...any) *CounterQuery {
	q.b.OrWhereRelation(relation, column, args...)
	return q
}

func (q *CounterQuery) WhereHasCount(relation string, callback func(*query.Builder), operator string, count int) *CounterQuery {
	q.b.WhereHasCount(relation, callback, operator, count)
	return q
}

func (q *CounterQuery) WhereBelongsTo(relationshipName string, related ...model.Entity) *CounterQuery {
	q.b.WhereBelongsTo(relationshipName, related...)
	return q
}

func (q *CounterQuery) Has(relation, operator string, count int, boolean string, callback func(*query.Builder)) *CounterQuery {
	q.b.Has(relation, operator, count, boolean, callback)
	return q
}

func (q *CounterQuery) OrHas(relation, operator string, count int) *CounterQuery {
	q.b.OrHas(relation, operator, count)
	return q
}

func (q *CounterQuery) DoesntHave(relation, boolean string, callback func(*query.Builder)) *CounterQuery {
	q.b.DoesntHave(relation, boolean, callback)
	return q
}

func (q *CounterQuery) OrDoesntHave(relation string) *CounterQuery {
	q.b.OrDoesntHave(relation)
	return q
}

func (q *CounterQuery) Select(columns ...any) *CounterQuery {
	q.b.Select(columns...)
	return q
}

func (q *CounterQuery) AddSelect(columns ...any) *CounterQuery {
	q.b.AddSelect(columns...)
	return q
}

func (q *CounterQuery) SelectRaw(expression string, bindings ...any) *CounterQuery {
	q.b.SelectRaw(expression, bindings...)
	return q
}

func (q *CounterQuery) Join(table any, first any, args ...any) *CounterQuery {
	q.b.Join(table, first, args...)
	return q
}

func (q *CounterQuery) GroupBy(groups ...any) *CounterQuery {
	q.b.GroupBy(groups...)
	return q
}

func (q *CounterQuery) OrderBy(column any, direction ...string) *CounterQuery {
	q.b.OrderBy(column, direction...)
	return q
}

func (q *CounterQuery) OrderByDesc(column any) *CounterQuery {
	q.b.OrderByDesc(column)
	return q
}

func (q *CounterQuery) Latest(column ...string) *CounterQuery {
	q.b.Latest(column...)
	return q
}

func (q *CounterQuery) Oldest(column ...string) *CounterQuery {
	q.b.Oldest(column...)
	return q
}

func (q *CounterQuery) Limit(value int) *CounterQuery {
	q.b.Limit(value)
	return q
}

func (q *CounterQuery) Offset(value int) *CounterQuery {
	q.b.Offset(value)
	return q
}

func (q *CounterQuery) ForPage(page, perPage int) *CounterQuery {
	q.b.ForPage(page, perPage)
	return q
}

func (q *CounterQuery) With(relations ...string) *CounterQuery {
	q.b.With(relations...)
	return q
}

func (q *CounterQuery) WithCount(relations ...string) *CounterQuery {
	q.b.WithCount(relations...)
	return q
}

func (q *CounterQuery) WithExists(relation string) *CounterQuery {
	q.b.WithExists(relation)
	return q
}

func (q *CounterQuery) WithSum(relation, column string) *CounterQuery {
	q.b.WithSum(relation, column)
	return q
}

func (q *CounterQuery) WithAvg(relation, column string) *CounterQuery {
	q.b.WithAvg(relation, column)
	return q
}

func (q *CounterQuery) WithMin(relation, column string) *CounterQuery {
	q.b.WithMin(relation, column)
	return q
}

func (q *CounterQuery) WithMax(relation, column string) *CounterQuery {
	q.b.WithMax(relation, column)
	return q
}

func (q *CounterQuery) Without(relations ...string) *CounterQuery {
	q.b.Without(relations...)
	return q
}

func (q *CounterQuery) WithoutGlobalScope(identifier string) *CounterQuery {
	q.b.WithoutGlobalScope(identifier)
	return q
}

func (q *CounterQuery) WithoutGlobalScopes(identifiers ...string) *CounterQuery {
	q.b.WithoutGlobalScopes(identifiers...)
	return q
}

// Get runs the query and returns the rows.
func (q *CounterQuery) Get(ctx context.Context, g auth.Grant, columns ...any) (CounterCollection, error) {
	rows, err := q.b.Get(ctx, g, columns...)
	return CounterCollectionOf(rows), err
}

// First returns the first row, or nil and no error when there is none.
func (q *CounterQuery) First(ctx context.Context, g auth.Grant, columns ...any) (*Counter, error) {
	e, err := q.b.First(ctx, g, columns...)
	return counterOf(e), err
}

func (q *CounterQuery) FirstOrFail(ctx context.Context, g auth.Grant, columns ...any) (*Counter, error) {
	e, err := q.b.FirstOrFail(ctx, g, columns...)
	return counterOf(e), err
}

func (q *CounterQuery) FirstWhere(ctx context.Context, g auth.Grant, column any, args ...any) (*Counter, error) {
	e, err := q.b.FirstWhere(ctx, g, column, args...)
	return counterOf(e), err
}

func (q *CounterQuery) FirstOrNew(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Counter, error) {
	e, err := q.b.FirstOrNew(ctx, g, attributes, values)
	return counterOf(e), err
}

func (q *CounterQuery) FirstOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Counter, error) {
	e, err := q.b.FirstOrCreate(ctx, g, attributes, values)
	return counterOf(e), err
}

func (q *CounterQuery) Find(ctx context.Context, g auth.Grant, id any, columns ...any) (*Counter, error) {
	e, err := q.b.Find(ctx, g, id, columns...)
	return counterOf(e), err
}

func (q *CounterQuery) FindOrFail(ctx context.Context, g auth.Grant, id any, columns ...any) (*Counter, error) {
	e, err := q.b.FindOrFail(ctx, g, id, columns...)
	return counterOf(e), err
}

func (q *CounterQuery) FindOrNew(ctx context.Context, g auth.Grant, id any, columns ...any) (*Counter, error) {
	e, err := q.b.FindOrNew(ctx, g, id, columns...)
	return counterOf(e), err
}

func (q *CounterQuery) FindMany(ctx context.Context, g auth.Grant, ids []any, columns ...any) (CounterCollection, error) {
	rows, err := q.b.FindMany(ctx, g, ids, columns...)
	return CounterCollectionOf(rows), err
}

func (q *CounterQuery) Sole(ctx context.Context, g auth.Grant, columns ...any) (*Counter, error) {
	e, err := q.b.Sole(ctx, g, columns...)
	return counterOf(e), err
}

func (q *CounterQuery) Create(ctx context.Context, g auth.Grant, attributes map[string]any) (*Counter, error) {
	e, err := q.b.Create(ctx, g, attributes)
	return counterOf(e), err
}

func (q *CounterQuery) ForceCreate(ctx context.Context, g auth.Grant, attributes map[string]any) (*Counter, error) {
	e, err := q.b.ForceCreate(ctx, g, attributes)
	return counterOf(e), err
}

func (q *CounterQuery) UpdateOrCreate(ctx context.Context, g auth.Grant, attributes, values map[string]any) (*Counter, error) {
	e, err := q.b.UpdateOrCreate(ctx, g, attributes, values)
	return counterOf(e), err
}

func (q *CounterQuery) Paginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (CounterCollection, *pagination.LengthAwarePage, error) {
	rows, meta, err := q.b.Paginate(ctx, g, perPage, page, opts, columns...)
	return CounterCollectionOf(rows), meta, err
}

func (q *CounterQuery) SimplePaginate(ctx context.Context, g auth.Grant, perPage, page int, opts pagination.Options, columns ...any) (CounterCollection, *pagination.Page, error) {
	rows, meta, err := q.b.SimplePaginate(ctx, g, perPage, page, opts, columns...)
	return CounterCollectionOf(rows), meta, err
}

func (q *CounterQuery) CursorPaginate(ctx context.Context, g auth.Grant, perPage int, cursor *pagination.Cursor, opts pagination.Options, columns ...any) (CounterCollection, *pagination.CursorPage, error) {
	rows, meta, err := q.b.CursorPaginate(ctx, g, perPage, cursor, opts, columns...)
	return CounterCollectionOf(rows), meta, err
}

func (q *CounterQuery) Chunk(ctx context.Context, g auth.Grant, count int, callback func(CounterCollection, int) (bool, error)) error {
	return q.b.Chunk(ctx, g, count, func(rows model.Rows, page int) (bool, error) {
		return callback(CounterCollectionOf(rows), page)
	})
}

func (q *CounterQuery) Each(ctx context.Context, g auth.Grant, count int, callback func(*Counter, int) (bool, error)) error {
	return q.b.Each(ctx, g, count, func(e model.Entity, index int) (bool, error) {
		return callback(counterOf(e), index)
	})
}

func (q *CounterQuery) Cursor(ctx context.Context, g auth.Grant) iter.Seq2[*Counter, error] {
	return func(yield func(*Counter, error) bool) {
		for e, err := range q.b.Cursor(ctx, g) {
			if !yield(counterOf(e), err) {
				return
			}
		}
	}
}

func (q *CounterQuery) Count(ctx context.Context, g auth.Grant, columns ...any) (int64, error) {
	return q.b.Count(ctx, g, columns...)
}

func (q *CounterQuery) Exists(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.Exists(ctx, g)
}

func (q *CounterQuery) DoesntExist(ctx context.Context, g auth.Grant) (bool, error) {
	return q.b.DoesntExist(ctx, g)
}

func (q *CounterQuery) Pluck(ctx context.Context, g auth.Grant, column string) ([]any, error) {
	return q.b.Pluck(ctx, g, column)
}

func (q *CounterQuery) Value(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.Value(ctx, g, column)
}

func (q *CounterQuery) ValueOrFail(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.ValueOrFail(ctx, g, column)
}

func (q *CounterQuery) SoleValue(ctx context.Context, g auth.Grant, column string) (any, error) {
	return q.b.SoleValue(ctx, g, column)
}

func (q *CounterQuery) Sum(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Sum(ctx, g, column)
}

func (q *CounterQuery) Avg(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Avg(ctx, g, column)
}

func (q *CounterQuery) Min(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Min(ctx, g, column)
}

func (q *CounterQuery) Max(ctx context.Context, g auth.Grant, column any) (any, error) {
	return q.b.Max(ctx, g, column)
}

func (q *CounterQuery) Update(ctx context.Context, g auth.Grant, values map[string]any) (int64, error) {
	return q.b.Update(ctx, g, values)
}

func (q *CounterQuery) Delete(ctx context.Context, g auth.Grant) (int64, error) {
	return q.b.Delete(ctx, g)
}

func (q *CounterQuery) Increment(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Increment(ctx, g, column, amount, extra)
}

func (q *CounterQuery) Decrement(ctx context.Context, g auth.Grant, column string, amount any, extra map[string]any) (int64, error) {
	return q.b.Decrement(ctx, g, column, amount, extra)
}

func (q *CounterQuery) Insert(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.Insert(ctx, g, values...)
}

func (q *CounterQuery) InsertOrIgnore(ctx context.Context, g auth.Grant, values ...map[string]any) (bool, error) {
	return q.b.InsertOrIgnore(ctx, g, values...)
}

func (q *CounterQuery) Upsert(ctx context.Context, g auth.Grant, values []map[string]any, uniqueBy, update []string) (int64, error) {
	return q.b.Upsert(ctx, g, values, uniqueBy, update)
}

func (q *CounterQuery) Touch(ctx context.Context, g auth.Grant, column ...string) (int64, error) {
	return q.b.Touch(ctx, g, column...)
}

// Rows converts the collection back to the core's rows.
func (c CounterCollection) Rows() model.Rows {
	out := make(model.Rows, len(c))
	for i, row := range c {
		out[i] = row
	}
	return out
}

func (c CounterCollection) ModelKeys() []any { return c.Rows().ModelKeys() }

func (c CounterCollection) Find(key any) *Counter { return counterOf(c.Rows().Find(key)) }

func (c CounterCollection) FindOrFail(key any) (*Counter, error) {
	e, err := c.Rows().FindOrFail(key)
	return counterOf(e), err
}

func (c CounterCollection) Contains(key any) bool { return c.Rows().Contains(key) }

func (c CounterCollection) Pluck(column string) []any { return c.Rows().Pluck(column) }

func (c CounterCollection) Only(keys ...any) CounterCollection {
	return CounterCollectionOf(c.Rows().Only(keys...))
}

func (c CounterCollection) Except(keys ...any) CounterCollection {
	return CounterCollectionOf(c.Rows().Except(keys...))
}

func (c CounterCollection) Unique() CounterCollection { return CounterCollectionOf(c.Rows().Unique()) }

func (c CounterCollection) Load(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().Load(ctx, g, relations...)
}

func (c CounterCollection) LoadMissing(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadMissing(ctx, g, relations...)
}

func (c CounterCollection) LoadCount(ctx context.Context, g auth.Grant, relations ...string) error {
	return c.Rows().LoadCount(ctx, g, relations...)
}

func (c CounterCollection) Fresh(ctx context.Context, g auth.Grant, with ...string) (CounterCollection, error) {
	rows, err := c.Rows().Fresh(ctx, g, with...)
	return CounterCollectionOf(rows), err
}

func (c CounterCollection) ToArray() []map[string]any { return c.Rows().ToArray() }

// Fresh reads the row again, as a new Counter; it shadows the untyped one the
// embedded model promotes.
func (row *Counter) Fresh(ctx context.Context, g auth.Grant, with ...string) (*Counter, error) {
	e, err := row.Model.Fresh(ctx, g, with...)
	return counterOf(e), err
}

// Replicate returns an unsaved copy of the row without its key; it shadows the
// untyped one the embedded model promotes.
func (row *Counter) Replicate(except ...string) (*Counter, error) {
	e, err := row.Model.Replicate(except...)
	return counterOf(e), err
}
